[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/nathanielc/marzipan"
